apiVersion: v1
kind: Secret
metadata:
  name: custom-secret
  namespace: bitwarden
type: Opaque
data:
  SA_PASSWORD: TXNzcWwhUGFzc3cwcmQ=
  globalSettings__installation__id: "base64-encoded-installation-id"
  globalSettings__installation__key: "base64-encoded-installation-key"
